### PR TITLE
install python-ldap

### PR DESCRIPTION
**Pull request by moisei**
ActiveDirectory Authentication requires python-ldap to be installed.
"SYSTEM SETTINGS/Authentication/Authentication Method/ActiveDirectory"

### CODE REVIEW

**Comment by trivia21** [comment]
adding rb extension not working, can you please provide pointer I will fix and contribute it back.

**Comment by moisei** [comment]
sure. it just was 7 months ago, so I don't remember what is rb? :)

**Comment by trivia21** [comment]
Thanks for the reply.
Adding reviewboard extension to your reviewboard docker is not working, need some input regarding that?
I had installed the extension in reviewboard container using easy_install and it's installed in the correct directory. But not reflecting in admin panel.
Also is it possible to add apache server to your reviewboard docker or I need to create one from scratch ? If yes can you provide any pointer to that too ?

**Comment by moisei** [comment]
i am not an author of this repository, i am just using it for a while for ~50 users and it works very well.
we don't use any extensions though, trieal version of powerpack worked well, until it expired.

**Comment by trivia21** [comment]
Great.
Are you using perforce ? How have you integrated perforce from the host
system?

Regards,
Satish

**Comment by moisei** [comment]
We use svn and it worked out of the box

**Pull request merged**
